AllCops:
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'bin/**/*'

Style/BlockComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringHashKeys:
  Enabled: true
Layout/AlignParameters:
  EnforcedStyle: 'with_fixed_indentation'
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'
Metrics/BlockLength:
  Enabled: false
Metrics/LineLength:
  Exclude:
    - 'config/**/*'
    - 'db/**/*'
    - 'spec/*_helper.rb'
    - 'spec/support/*'
