AllCops:
  Exclude:
    - "node_modules/**/*"
    - "vendor/**/*"
    - ".git/**/*"
    - "bin/**/*"

Style/BlockComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringHashKeys:
  Enabled: true
Metrics/BlockLength:
  Enabled: false
Metrics/LineLength:
  Exclude:
    - "config/**/*"
    - "db/**/*"
    - "spec/*_helper.rb"
    - "spec/support/*"
