dist: xenial

language: ruby
rvm:
  - 2.5.3

branches:
  only:
    - master
    - /.*-runci$/

cache:
  directories:
    - vendor/bundle
    - node_modules
    - $HOME/.nvm

addons:
  postgresql: '10'

before_install:
  - nvm install --lts=carbon
  - node --version

install:
  - bundle install --deployment --without development production --jobs=3 --retry=3
  - yarn

before_script:
  - psql -c 'create database clvoz_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
  - cp config/credentials.travis.yml.enc config/credentials.yml.enc
  - rake db:schema:load

script:
  - yarn eslint
  - yarn stylelint
  - rubocop
  - rake spec
