version: '3.7'
services:
  nginx-production:
    image: moonlight8978/clvoz:nginx-production
    deploy:
      placement:
        constraints: [node.role == manager]
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    command: ['nginx', '-g', 'daemon off;']
    volumes:
      - /data/clvoz/production/nginx/log:/var/log/nginx
    networks:
      - public
      - private

  server-production:
    image: moonlight8978/clvoz:server-production
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    env_file:
      - .env
    volumes:
      - /data/clvoz/production/rails/log:/var/www/clvoz/log
      - /data/clvoz/production/rails/storage:/var/www/clvoz/storage
    command: puma -C config/puma.rb
    networks:
      - public
      - private

  db:
    image: postgres:10.6-alpine
    env_file:
      - .env
    volumes:
      - /data/clvoz/production/postgresql/data:/var/lib/postgresql/data
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - private

networks:
  public:
  private:
