version: '3.7'
services:
  server:
    build:
      context: .
      args:
        APP_PATH: $APP_PATH
    env_file:
      - .env
    ports:
      - ${HOST_PORT}:3000
    command: rails s
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      - .:$APP_PATH
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - /data/app/clvoz/db:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - ${HOST_DB_PORT}:5432

  pgadmin:
    image: dpage/pgadmin4:latest
    volumes:
      - /data/pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@framgia.com
      PGADMIN_DEFAULT_PASSWORD: 1111
    ports:
      - ${HOST_PGADMIN_PORT}:80
    depends_on:
      - db
