version: '3.7'
services:
  nginx-production:
    image: moonlight8978/clvoz:nginx-production
    build:
      context: .
      target: webserver
      args:
        RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    env_file:
      - .env
    restart: always
    ports:
      - 80:80
      - 443:443
    command: ['nginx', '-g', 'daemon off;']
    volumes:
      - /data/clvoz/production/nginx/log:/var/log/nginx
    depends_on:
      - server-production

  server-production:
    image: moonlight8978/clvoz:server-production
    build:
      context: .
      target: appserver
      args:
        RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    env_file:
      - .env
    restart: always
    volumes:
      - /data/clvoz/production/rails/log:/var/www/clvoz/log
      - /data/clvoz/production/rails/storage:/var/www/clvoz/storage
    command: puma -C config/puma.rb
    depends_on:
      - db

  db:
    image: postgres:10.6-alpine
    env_file:
      - .env
    volumes:
      - /data/clvoz/production/postgresql/data:/var/lib/postgresql/data
    restart: always
