default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= Rails.application.credentials.DATABASE_HOST %>
  port: <%= Rails.application.credentials.DATABASE_PORT %>
  username: <%= Rails.application.credentials.DATABASE_USERNAME %>
  password: <%= Rails.application.credentials.DATABASE_PASSWORD %>

development:
  <<: *default
  database: clVoz_development
test:
  <<: *default
  database: clVoz_test
production:
  <<: *default
  database: clVoz_production
