# PostgreSQL. Versions 9.1 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= Rails.application.credentials.DATABASE_HOST %>
  port: <%= Rails.application.credentials.DATABASE_PORT %>
  username: <%= Rails.application.credentials.DATABASE_USERNAME %>
  password: <%= Rails.application.credentials.DATABASE_PASSWORD %>

development:
  <<: *default
  database: clVoz_development
test:
  <<: *default
  database: clVoz_test
production:
  <<: *default
  database: clVoz_production
  host: <%= Rails.application.credentials.DATABASE_HOST_PRODUCTION %>
  port: <%= Rails.application.credentials.DATABASE_PORT_PRODUCTION %>
  username: <%= Rails.application.credentials.DATABASE_USERNAME_PRODUCTION %>
  password: <%= Rails.application.credentials.DATABASE_PASSWORD_PRODUCTION %>
